// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DashBoord_Ecomerce.Models;

[Table("categories")]
public partial class Category
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }
}