// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DashBoord_Ecomerce.Models;

[Table("orders")]
[Index("PayId", Name = "IX_orders_Pay_ID")]
[Index("ProductId", Name = "IX_orders_Product_ID")]
[Index("UserId", Name = "IX_orders_User_ID")]
public partial class Order
{
    [Key]
    public int Id { get; set; }

    [Column("User_ID")]
    public int UserId { get; set; }

    [Column("Product_ID")]
    public int ProductId { get; set; }

    public int Quentity { get; set; }

    [Column("Pay_ID")]
    public int PayId { get; set; }

    public double Total { get; set; }

    public DateTime DateTime { get; set; }

    [ForeignKey("PayId")]
    [InverseProperty("Orders")]
    public virtual Payment Pay { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("Orders")]
    public virtual Product Product { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Orders")]
    public virtual User User { get; set; }
}