// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DashBoord_Ecomerce.Models;

[Table("payments")]
public partial class Payment
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    [InverseProperty("Pay")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}