// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DashBoord_Ecomerce.Models;

[Table("products")]
public partial class Product
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    public int Quentity { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }

    public string Description { get; set; }

    [Column("CategoryID")]
    public int CategoryId { get; set; }

    public byte[]? Image { get; set; }
    [NotMapped]
    public IFormFile? formFile { get; set; }

    [NotMapped]
    public string? ImageUrl
    {
        get
        {
            if (Image != null)
            {
                string base64 = Convert.ToBase64String(Image, 0, Image.Length);
                return "data:image/png;base64," + base64;
            }
            return string.Empty;
        }
    }

    [InverseProperty("Product")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}