// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DashBoord_Ecomerce.Models;

[Table("users")]
public partial class User
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string Email { get; set; }

    [Required]
    public string Password { get; set; }

    [Required]
    [Column("Re_Password")]
    public string RePassword { get; set; }

    [Required]
    public string Number { get; set; }

    public byte[] ImageBytes { get; set; }
    [NotMapped]
    public IFormFile? formFile { get; set; }
    [NotMapped]
    public string ImageUrl
    {
        get
        {
            if (ImageBytes != null)
            {
                string base64 = Convert.ToBase64String(ImageBytes, 0, ImageBytes.Length);
                return "data:image/png;base64," + base64;
            }
            return string.Empty;
        }
    }

    [InverseProperty("User")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}